server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA simples / arquivos estáticos
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Sem cache para o app (facilita atualizações)
    location ~* \.(html|js|css)$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }

    client_max_body_size 50m;
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
